INSERT IGNORE INTO words (word)
VALUES ('Tree'),
       ('Water'),
       ('Light'),
       ('House'),
       ('Dream'),
       ('Time'),
       ('Flame'),
       ('Cloud'),
       ('Stone'),
       ('Sound'),
       ('Sun'),
       ('Moon'),
       ('Star'),
       ('Sky'),
       ('Rain'),
       ('Forest'),
       ('Fire'),
       ('Ice'),
       ('Gold'),
       ('Wind'),
       ('Sea'),
       ('Mountain'),
       ('Shadow'),
       ('Leaf'),
       ('Flower'),
       ('Grass'),
       ('Road'),
       ('Silence'),
       ('Power'),
       ('Word'),
       ('Line'),
       ('Mirror'),
       ('Thread'),
       ('Color'),
       ('Shape'),
       ('Scent'),
       ('Path'),
       ('Gate'),
       ('Tower'),
       ('Room'),
       ('Book'),
       ('Note'),
       ('Pen'),
       ('Map'),
       ('Roof'),
       ('Clock'),
       ('Night');

INSERT IGNORE INTO sentences (sentence)
VALUES ('The tree is tall.'),
       ('I drink water.'),
       ('The light shines.'),
       ('The house is big.'),
       ('I had a dream.'),
       ('Time passes quickly.'),
       ('The flame burned brightly.'),
       ('A cloud floats.'),
       ('I found a stone.'),
       ('The sound is loud.'),
       ('The sun is hot.'),
       ('The moon is full.'),
       ('A star twinkles.'),
       ('The sky is blue.'),
       ('Rain falls softly.'),
       ('The forest is dense.'),
       ('Fire is dangerous.'),
       ('Ice is cold.'),
       ('Gold is precious.'),
       ('The wind blows.'),
       ('The sea is calm.'),
       ('The mountain is high.'),
       ('My shadow moves.'),
       ('A leaf fell.'),
       ('The flower blooms.'),
       ('Grass grows fast.'),
       ('The road is long.'),
       ('Silence is golden.'),
       ('Power is strong.'),
       ('I read a word.'),
       ('Draw a line.'),
       ('Look in the mirror.'),
       ('The thread broke.'),
       ('The color is bright.'),
       ('The shape is round.'),
       ('The scent is sweet.'),
       ('Follow the path.'),
       ('The gate is closed.'),
       ('The tower stands tall.'),
       ('The room is clean.'),
       ('I read a book.'),
       ('Write a note.'),
       ('The pen is blue.'),
       ('I checked the map.'),
       ('The tree needs water.'),
       ('The light shines in the house.'),
       ('I dream about time.'),
       ('The flame scares the cloud.'),
       ('The stone makes a sound.'),
       ('The sun and moon shine.'),
       ('The star lights the sky.'),
       ('Rain falls in the forest.'),
       ('Fire melts the ice.'),
       ('Gold glitters in the wind.'),
       ('The sea meets the mountain.'),
       ('The shadow covers the leaf.'),
       ('The flower grows in the grass.'),
       ('The road is silence.'),
       ('A word has power.'),
       ('Draw a line on the mirror.'),
       ('The thread has color.'),
       ('The shape affects the scent.'),
       ('The path leads to the gate.'),
       ('The tower has a room.'),
       ('I wrote a note in the book.'),
       ('I used a pen on the map.'),
       ('The tree caught flame.'),
       ('Water mixes with rain.'),
       ('Light shines from the star.'),
       ('The house has a roof.'),
       ('The dream follows the shadow.'),
       ('Time ticks on the clock.'),
       ('The stone lies on the road.'),
       ('The sun warms the flower.'),
       ('The moon lights the night.'),
       ('The cloud moves with the wind.'),
       ('The forest hides the path.'),
       ('Fire burns the tower.'),
       ('Ice floats on the sea.'),
       ('Gold sparkles on the leaf.'),
       ('The wind carries the scent.'),
       ('The tree drinks water under the sun.'),
       ('The moon and star fill the sky.'),
       ('Rain falls from the cloud in the wind.'),
       ('Fire and ice ignite the flame.'),
       ('The flower grows among the grass and leaf.'),
       ('The road leads to the path and gate.'),
       ('I wrote a note in the book with a pen.');

INSERT IGNORE INTO sentence_words (sentence_id, word_id)
SELECT s.id, w.id
FROM sentences s
         JOIN words w
              ON LOWER(s.sentence) COLLATE utf8mb4_general_ci
                  LIKE CONCAT('%', LOWER(w.word) COLLATE utf8mb4_general_ci, '%');